source "https://rubygems.org"

# To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  #gem "jekyll-feed", "~> 0.12"
end

# Used for locally serving the website.
gem "webrick", ">= 1.7"
